import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { useQuery } from '@tanstack/react-query'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { data, isLoading, isFetching, error } = useQuery(['/notice'], () => axios.get('https://211.206.251.66:7000/Notice'))

  console.log(
    'data:', data, 
    'isFetching:', isFetching
  )
  if (isLoading) return 'Loading...'

  if (error) return 'An error has occurred: ' + error.message

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
      </main>
    </>
  )
}
